### ISSUE TITLE
Move Elisp batch file from python

### ISSUE THREAD

**Issue by conao3** [riscy/melpazoid#3]
As https://github.com/melpa/melpa/pull/6728, melpa have no python 3.6.
we can't expect `python`, but we can expect `Emacs` :).
Elisp is Turing complete and, fortunately, or unfortunately, can even execute external commands.
We should migrate from `python` to the Elisp batch file while the project is still small.

https://www.emacswiki.org/emacs/BatchMode

**Comment by riscy** [comment]
Agreed -- I'd like to see less python and more elisp where possible so that it can be run as a script.  Actually you may have seen that the Docker container -- once built -- just runs `/usr/local/bin/emacs --script melpazoid.el`.  More checks could happen inside that call to /usr/bin/emacs, rather than in python, but I am a bit stronger in python.

Even if we do get rid of python, though, I feel like there should still be a big chunk of this that relies on Docker, so that we can do cleanroom builds in consistent environments so that detected problems are easier to track down.

**Comment by riscy** [comment]
> As melpa/melpa#6728, melpa have no python 3.6.

Incidentally, it turned out that it was easy to switch to Python 3.6, since none of the build was relying on the ruby base.  That will teach me to comment on my own failed experiments. ;)

**Comment by conao3** [comment]
I think MELPA in Travis should run in `language: generic`.
But if MELPA moving to GitHub Actions, we don't need to discuss this...

**Comment by riscy** [comment]
Hi again @conao3 - I'm just combing through melpazoid issues.  I think I have ultimately done the *opposite* of what you suggested in this issue, and increased reliance on python as time has gone by.  For better or worse, that's probably the state melpazoid will remain in unless I chase after a big refactor.

I'll mark this one as closed for now, but I still acknowledge that a pure Emacs solution would've been preferable.
